# Generated by Django 5.0.7 on 2024-08-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itementry',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itementry',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='itementry',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritioninfo',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritioninfo',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='nutritioninfo',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
