# Generated by Django 5.0.7 on 2024-08-28 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bmicalculation',
            name='user',
        ),
        migrations.AlterField(
            model_name='bmicalculation',
            name='category',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='itementry',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritioninfo',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritioninfo',
            name='sodium',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='nutritioninfo',
            name='sugar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='itementry',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='nutrition.category'),
        ),
        migrations.AddField(
            model_name='nutritioninfo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_info', to='nutrition.category'),
        ),
    ]
