# Generated by Django 5.0.7 on 2024-08-29 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_category_remove_bmicalculation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritioninfo',
            old_name='item_name',
            new_name='name',
        ),
    ]
