# Generated by Django 5.0.7 on 2024-08-19 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_userprofile_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bmicalculation',
            name='user',
        ),
    ]
