# Generated by Django 5.0.7 on 2024-08-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_rename_item_name_nutritioninfo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutritioninfo',
            old_name='name',
            new_name='item_name',
        ),
    ]
