# Generated by Django 5.0.7 on 2024-09-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_rename_name_nutritioninfo_item_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itementry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nutritioninfo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
