# Generated by Django 5.0.7 on 2024-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_userprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmicalculation',
            name='category',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
