# Generated by Django 5.0.7 on 2024-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_category_itementry_category_nutritioninfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninfo',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
