# Generated by Django 5.0.7 on 2024-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0007_nutritioninfo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nutrition_images/'),
        ),
    ]
