# Generated by Django 5.0.7 on 2024-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0010_alter_usersubmission_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritioninfo',
            name='is_weight_based',
            field=models.BooleanField(default=True),
        ),
    ]
