# Generated by Django 5.0.7 on 2024-10-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0012_remove_userprofile_age_remove_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutritioninfo',
            name='is_weight_based',
        ),
        migrations.AddField(
            model_name='nutritioninfo',
            name='unit_weight',
            field=models.FloatField(default=100),
        ),
    ]
